### ISSUE TITLE
[EPIC 4] Add query utils for analysis aggregation.

### ISSUE THREAD

**Issue by mdjohns** [ualr-htcpcp/dcia#55]
In order to populate the visualizations used in Epic 4, we need query functions built to aggregate this data. We should create a file `utils/queries.js` and `export` each query to be used by the API endpoints. (See the format of other `util` items such as `util/email.js` for comparison).

### Queries from functional requirements
- [UC 4.1] Mean SO scores over time (filtered by specified term range)
- [UC 4.2] SO scores by course level (filtered by specified term range)
- [UC 4.3] SO scores by course for a term (we only specify current term, but term would be a necessary parameter for this query)
- [UC 4.4] SO scores by instructor for a term (again, we only specify current term, but this would be a needed parameter)

Potential method of attack:
- [x] Seed database with data (~100 assessments)
- [x] Use MongoDB Compass to build the appropriate queries to gather the data needed
- [ ] "Translate" those queries to MongooseJS code (ex. `const foo = await bar.find({<query here>}).lean()`)
- [ ] Organize those queries in `utils/queries.js`
