### ISSUE TITLE
Pre-demo checklist

### ISSUE THREAD

**Issue by mdjohns** [ualr-htcpcp/dcia#84]
- [x] Enable email services on production Heroku instance
  - [ ] Test all email services in production before demo
- [ ] Sanity check math for all analysis data. Could be accomplished by removing assessment data from the production database and re-entering a small amount of new data.
- [ ] Re-seed database for client demo.
  - [ ] Take note of user with instructor access to demo analysis graph scoping.
